### ISSUE TITLE
Add `supported_platforms` for plugins

### ISSUE THREAD

**Issue by brynary** [qltysh/qlty#1220]
Certain plugins may not be compatible with all platforms that we run on. For example, we have identified issues with Hadolint on MacOS, and we have identified issues with swiftlint on non-MacOS systems.

Add a `supported_platforms` array key to the plugin definition:

```toml
[plugins.definitions.swiftlint]
supported_platforms = ["macos"]
# ...
```

Valid array values are `"macos"`, `"linux"`, and `"windows"`.

If `supported_platforms` is empty, treat it as _all_ platforms. If `supported_platforms` is not blank:

1. `qlty init` should only enable the plugin if it is on a supported platform.
2. The planner should skip the plugin when running on a supported platform (if the platform is unsupported on the current platform, log an `info!`)

**Comment by noahd1** [comment]
@brynary 

It occurred to me that `supported_platforms` is probably more an attribute of a version of a plugin than the plugin itself, but perhaps we do not make that distinction today. E.g. what happens / how do we handle if e.g. `1.0` of a plugin's output differs from `2.0`?

**Comment by brynary** [comment]
The way we handle that is with multiple driver definitions. Driver definitions can target version ranges of plugins

So if we defined the supported platforms data at the driver level instead of the plugin level then you could model this

(One plugin has one or more drivers)

**Comment by noahd1** [comment]
@brynary you wrote:

> The planner should skip the plugin when running on a supported platform (if the platform is unsupported on the current platform, log an info!)

I'm assuming you meant to write that the planner should skip the plugin when running on an _unsupported_ platform?

**Comment by noahd1** [comment]
See https://github.com/qltysh/qlty/pull/1319
