### ISSUE TITLE
Bug: Error parsing output from clippy

### ISSUE THREAD

**Issue by brynary** [qltysh/qlty#1225]
### What happened?

Error parsing output from clippy

```
Clippy output includes success: false, ClippyIssue { message: None, success: Some(false), manifest_path: None, package_id: None, package_name: "", path_prefix: "" }, raw line: "{\"reason\":\"build-finished\",\"success\":false}"
```

### What did you expect to happen?

No parse error

### Can you reproduce the problem?

Yes, consistently

### CLI Version

qlty 0.452.0 (3124098)

### Relevant log output

```shell
https://qlty.sh/gh/qltysh/projects/qlty/builds/a25e2b82-eff1-46a1-ae89-93fc15ffdc03
```

**Comment by marschattha** [comment]
So we are throwing this error ourselves in case clippy failed to compile code. 
https://github.com/qltysh/qlty/blob/main/qlty-check/src/parser/clippy.rs#L114

What do you think would be the desired output in this case? 
Should we log a warning message onto the terminal and logs? Something like 
```
Clippy failed to compile your code, either there is an error in your code or 
Clippy version is incompatible with your project.
```

**Comment by brynary** [comment]
Hmm, let's take the qlty CLI out of the picture for the moment.


If the same problem was happening (compilation failure) and the user ran Clippy by hand without qlty, what output would they get?

I think that's a good place to start because that tells us how a user would debug.
