### ISSUE TITLE
Plugin request: reek

### ISSUE THREAD

**Issue by tim-gq** [qltysh/qlty#1257]
### What is the name of the static analysis tool?

reek

### Where is the tool's documentation published?

https://github.com/troessner/reek

### Where are releases published?

https://github.com/troessner/reek/tags

### What programming languages or other file types does the tool support?

Ruby, unsure on rest

### What type of tool is this?

Other

### Additional context

I don't know too much about it yet - just that our current codeclimate config is using it, so having Qlty support it means we wouldn't lose the integration when migrating from CC to Qlty.

It's support is a bit broken in CC - in that it's locked to older versions that don't support ruby 3.2 syntax and silently* errors on some files..

**Comment by noahd1** [comment]
See https://github.com/qltysh/qlty/pull/1265
