### ISSUE TITLE
Bug: Migration Assistance

### ISSUE THREAD

**Issue by davemattcsu** [qltysh/qlty#1300]
### What happened?

Who do I contact about migration from CodeClimate and support for the free educational plan that I used in the past?  I've already sent a note to support-quality@codeclimate.com about setting up an organization for the spring semester.

 

### What did you expect to happen?

email response

### Can you reproduce the problem?

No

### CLI Version

NA

### Relevant log output

```shell

```

**Comment by brynary** [comment]
Hi Dave -- I saw your email today and responded to it. Going to close this out and we can continue  the conversation over email. 

Best, -Bryan

**Comment by davemattcsu** [comment]
Thanks!
